In [16]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.metrics import root_mean_squared_error
from sklearn import metrics
df= pd.read_csv("C:/Users/ADMIN/Downloads/Breast_Cancer_data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [2]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [3]:
df.drop('Unnamed: 32',axis=1,inplace=True)

In [4]:
y=df['diagnosis']
x=df.drop('diagnosis',axis=1)

In [5]:
from sklearn.preprocessing import LabelEncoder
x= pd.get_dummies(x)

# Encode target variable
le = LabelEncoder()
y = le.fit_transform(y)

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=11)

In [7]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((426, 31), (143, 31), (426,), (143,))

In [8]:
lr=LogisticRegression()
model=lr.fit(x_train,y_train)

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [9]:
y_pred=model.predict(x_test)
df=pd.DataFrame({'y_pred':y_pred,'y_test':y_test})
df

     y_pred  y_test
0         1       1
1         1       1
2         1       1
3         1       1
4         1       1
..      ...     ...
138       1       1
139       0       0
140       1       1
141       0       0
142       0       0

[143 rows x 2 columns]

In [14]:
print("LogisticRegression Accuracy:", metrics.accuracy_score(y_test, y_pred))

LogisticRegression Accuracy: 0.9370629370629371

In [17]:
dtc = DecisionTreeClassifier(random_state=42)
dtc.fit(x_train, y_train)
y_pred_dt = dtc.predict(x_test)

print("Decision Tree Accuracy:", metrics.accuracy_score(y_test, y_pred_dt))

Decision Tree Accuracy: 0.951048951048951

In [18]:
rfc = RandomForestClassifier(random_state=42)
rfc.fit(x_test, y_test)
x_pred_rf = rfc.predict(x_train)

print("Random Forest Accuracy:", metrics.accuracy_score(y_train, x_pred_rf))

Random Forest Accuracy: 0.9366197183098591