## 2.Using pandas module perform the following operations:

In [5]:
import pandas as pd
import numpy as np
marks = {'Chemistry': [67,90,66,32],
'Physics': [45,92,72,40],
'Mathematics': [50,87,81,12],
'English': [19,90,72,68]}
marks_df = pd.DataFrame(marks, index = ['Subodh', 'Ram', 'Abdul', 'John'])
marks_df

        Chemistry  Physics  Mathematics  English
Subodh         67       45           50       19
Ram            90       92           87       90
Abdul          66       72           81       72
John           32       40           12       68

### a) Aggregation and grouping,time series operations and pivot and melt functions:

### Aggreagations functions:

In [9]:
marks_df['Chemistry'].agg(['mean','median','max','min','std','sum'])

mean       63.750000
median     66.500000
max        90.000000
min        32.000000
std        23.893863
sum       255.000000
Name: Chemistry, dtype: float64

### Grouping

In [10]:
marks_df.groupby('Physics')['Mathematics'].sum()

Physics
40    12
45    50
72    81
92    87
Name: Mathematics, dtype: int64

In [14]:
a=marks_df.groupby(['Chemistry','English']).sum()
a

                   Physics  Mathematics
Chemistry English
32        68            40           12
66        72            72           81
67        19            45           50
90        90            92           87

### Time series

In [16]:
range_date=pd.date_range(start='1/1/2020',end='1/10/2025',freq='D')
range_date

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', length=1837, freq='D')

In [18]:
month=pd.date_range(start='1/1/2020',end='1/10/2025',freq='ME')
month

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31',
               '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31',
               '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31',
               '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31'],
              dtype='datetime64[ns]', freq='ME')

### b) Demonstrate map,filter,reduce and lambda functions with dataframe

In [22]:
Grade_marks=list(map(lambda x:x+10,marks_df['Chemistry']))
print("Add Grade marks to Chemistry subject:")
Grade_marks

Add Grade marks to Chemistry subject:

[77, 100, 76, 42]